# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('super_admin', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='accounts.User')),
            ],
        ),
    ]
